-- Базовая схема RealHelpDesk — снимок ddl-auto Hibernate (2026-10-05), PostgreSQL 15.
--
-- Обязательно должен совпадать с entity в src/main/java: docker-compose держит
-- spring.jpa.hibernate.ddl-auto=validate, и Hibernate валит старт при расхождении
-- таблиц/колонок/типов. CHECK-ограничения фиксируют значения enum — новое значение
-- enum в коде требует отдельного changeset с пересозданием ограничения.
--
-- Выполняется changeset'ом 001-baseline-schema.xml: на базе, где таблицы уже есть,
-- изменения помечается выполненным (precondition), здесь ничего не применяется.

-- ---------------------------------------------------------------------------
-- Пользователи и токены
-- ---------------------------------------------------------------------------

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    external_id BIGINT,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    middle_name VARCHAR(255),
    additional_info VARCHAR(5000),
    email VARCHAR(255) NOT NULL,
    verify_email_token BIGINT,
    recovery_passwd_token BIGINT,
    is_email_verified BOOLEAN NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    user_role VARCHAR(255),
    user_status VARCHAR(255),
    user_platform_source VARCHAR(255),
    token_version INTEGER NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    portal_cunt_limit INTEGER,
    portal_shared_users_count_limit INTEGER,
    version INTEGER NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_user_role_check CHECK (user_role IN ('ROLE_NONE', 'ROLE_ADMIN', 'ROLE_USER')),
    CONSTRAINT users_user_status_check CHECK (user_status IN ('ACTIVE', 'BLOCKED', 'DISABLED')),
    CONSTRAINT users_user_platform_source_check CHECK (user_platform_source IN ('LOCAL', 'TELEGRAM'))
);

-- Только SHA-256 хеш (64 символа), сырой токен живёт в cookie.
CREATE TABLE jwt_tokens (
    uuid UUID NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    user_id BIGINT NOT NULL,
    token_refresh VARCHAR(64) NOT NULL,
    status VARCHAR(255),
    CONSTRAINT jwt_tokens_pkey PRIMARY KEY (uuid),
    CONSTRAINT jwt_tokens_token_refresh_key UNIQUE (token_refresh),
    CONSTRAINT jwt_tokens_status_check CHECK (status IN ('ACTIVE', 'LOGOUT', 'BLOCKED', 'REVOKED', 'SUSPECTED', 'PASSWD_CHANGE'))
);

ALTER TABLE jwt_tokens
    ADD CONSTRAINT fk_jwt_tokens_user_id FOREIGN KEY (user_id) REFERENCES users (id);

-- ---------------------------------------------------------------------------
-- Порталы и доступ
-- ---------------------------------------------------------------------------

CREATE TABLE portals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    owner_id BIGINT NOT NULL,
    is_deleted BOOLEAN NOT NULL,
    time_delete TIMESTAMP(6) WITH TIME ZONE,
    is_public BOOLEAN NOT NULL,
    version INTEGER NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT portals_pkey PRIMARY KEY (id),
    CONSTRAINT portals_owner_id_name_key UNIQUE (owner_id, name)
);

ALTER TABLE portals
    ADD CONSTRAINT fk_portals_owner_id FOREIGN KEY (owner_id) REFERENCES users (id);

CREATE TABLE portal_access (
    portal_id BIGINT NOT NULL,
    allowed_user_id BIGINT,
    CONSTRAINT portal_access_portal_id_allowed_user_id_key UNIQUE (portal_id, allowed_user_id)
);

ALTER TABLE portal_access
    ADD CONSTRAINT fk_portal_access_portal_id FOREIGN KEY (portal_id) REFERENCES portals (id);

-- ---------------------------------------------------------------------------
-- Заявки и сообщения
-- ---------------------------------------------------------------------------

CREATE TABLE ticket_model (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    assigned_user_id BIGINT,
    author_id BIGINT NOT NULL,
    portal_id BIGINT NOT NULL,
    ticket_priority VARCHAR(255),
    ticket_status VARCHAR(255),
    ticket_live_status VARCHAR(255),
    who_delete BIGINT,
    time_delete TIMESTAMP(6) WITH TIME ZONE,
    version INTEGER NOT NULL,
    access_status SMALLINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT ticket_model_pkey PRIMARY KEY (id),
    CONSTRAINT ticket_model_access_status_check CHECK (access_status >= 0 AND access_status <= 1),
    CONSTRAINT ticket_model_ticket_priority_check CHECK (ticket_priority IN ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'NONE')),
    CONSTRAINT ticket_model_ticket_status_check CHECK (ticket_status IN ('OPEN', 'CLOSED', 'IN_PROGRESS')),
    CONSTRAINT ticket_model_ticket_live_status_check CHECK (ticket_live_status IN ('ACTIVE', 'DELETE'))
);

ALTER TABLE ticket_model
    ADD CONSTRAINT fk_ticket_model_assigned_user_id FOREIGN KEY (assigned_user_id) REFERENCES users (id);

ALTER TABLE ticket_model
    ADD CONSTRAINT fk_ticket_model_author_id FOREIGN KEY (author_id) REFERENCES users (id);

ALTER TABLE ticket_model
    ADD CONSTRAINT fk_ticket_model_portal_id FOREIGN KEY (portal_id) REFERENCES portals (id);

CREATE TABLE message_model (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    version INTEGER NOT NULL,
    ticket_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    message_text TEXT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT message_model_pkey PRIMARY KEY (id)
);

ALTER TABLE message_model
    ADD CONSTRAINT fk_message_model_ticket_id FOREIGN KEY (ticket_id) REFERENCES ticket_model (id);

ALTER TABLE message_model
    ADD CONSTRAINT fk_message_model_author_id FOREIGN KEY (author_id) REFERENCES users (id);

-- ---------------------------------------------------------------------------
-- Оповещения и настройки уведомлений
-- ---------------------------------------------------------------------------

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    is_read BOOLEAN NOT NULL,
    recipient_id BIGINT NOT NULL,
    event VARCHAR(255) NOT NULL,
    ticket_id BIGINT,
    portal_id BIGINT,
    title VARCHAR(255),
    group_id BIGINT,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT notifications_pkey PRIMARY KEY (id),
    CONSTRAINT notifications_event_check CHECK (event IN ('NEW_TICKET', 'NEW_MESSAGE', 'NEW_SYSTEM_MESSAGE', 'NEW_TICKET_OR_MESSAGE',
        'NEW_PORTAL', 'CHANGE_TICKET', 'RECOVERY_PASSWORD', 'TICKET_DELETED', 'PORTAL_DELETED', 'NONE'))
);

CREATE INDEX idx_notifications_recipient_created ON notifications (recipient_id, created_at);
CREATE INDEX idx_notifications_recipient_read ON notifications (recipient_id, is_read);

CREATE TABLE user_notification_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    repeat_enabled BOOLEAN NOT NULL,
    repeat_interval_minutes INTEGER NOT NULL,
    CONSTRAINT user_notification_preferences_pkey PRIMARY KEY (id),
    CONSTRAINT user_notification_preferences_user_id_key UNIQUE (user_id)
);

CREATE TABLE user_notification_preferences_events (
    preferences_id BIGINT NOT NULL,
    event VARCHAR(255) NOT NULL,
    CONSTRAINT user_notification_preferences_events_pkey PRIMARY KEY (preferences_id, event),
    CONSTRAINT user_notification_preferences_events_event_check CHECK (event IN ('NEW_TICKET', 'NEW_MESSAGE', 'NEW_SYSTEM_MESSAGE',
        'NEW_TICKET_OR_MESSAGE', 'NEW_PORTAL', 'CHANGE_TICKET', 'RECOVERY_PASSWORD', 'TICKET_DELETED', 'PORTAL_DELETED', 'NONE'))
);

ALTER TABLE user_notification_preferences_events
    ADD CONSTRAINT fk_user_notification_preferences_events_preferences_id
    FOREIGN KEY (preferences_id) REFERENCES user_notification_preferences (id);

-- ---------------------------------------------------------------------------
-- Email: журнал отправки и стоп-лист рассылок
-- ---------------------------------------------------------------------------

CREATE TABLE email_log (
    id BIGINT NOT NULL,
    version INTEGER NOT NULL,
    notification_event VARCHAR(255),
    recipient VARCHAR(255),
    sender VARCHAR(255),
    title VARCHAR(255),
    sent_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT email_log_pkey PRIMARY KEY (id),
    CONSTRAINT email_log_notification_event_check CHECK (notification_event IN ('NEW_TICKET', 'NEW_MESSAGE', 'NEW_SYSTEM_MESSAGE',
        'NEW_TICKET_OR_MESSAGE', 'NEW_PORTAL', 'CHANGE_TICKET', 'RECOVERY_PASSWORD', 'TICKET_DELETED', 'PORTAL_DELETED', 'NONE'))
);

-- @GeneratedValue(strategy = AUTO) у EmailLog: sequence с increment 50,
-- как его создаёт Hibernate (pooled-оптимизатор считает с шагом 50).
CREATE SEQUENCE email_log_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE unsubscribed_emails (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(255),
    mute_event VARCHAR(255) NOT NULL,
    in_stop_list_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT unsubscribed_emails_pkey PRIMARY KEY (id),
    CONSTRAINT unsubscribed_emails_email_key UNIQUE (email),
    CONSTRAINT unsubscribed_emails_mute_event_check CHECK (mute_event IN ('NEW_TICKET', 'NEW_MESSAGE', 'NEW_SYSTEM_MESSAGE',
        'NEW_TICKET_OR_MESSAGE', 'NEW_PORTAL', 'CHANGE_TICKET', 'RECOVERY_PASSWORD', 'TICKET_DELETED', 'PORTAL_DELETED', 'NONE'))
);
