-- Вложения сообщений заявок (файлы в MinIO, здесь — только метаданные).
--
-- Обязательно должен совпадать с entity AttachmentModel
-- (src/main/java/com/ukhanov/realhelpdesk/domain/attachment/model/AttachmentModel.java):
-- docker-compose держит spring.jpa.hibernate.ddl-auto=validate, и Hibernate валит
-- старт при расхождении таблиц/колонок/типов.
--
-- Содержимое файла в БД не ложится: колонка storage_key — ключ объекта в бакете
-- MinIO, уникальный, чтобы повторная загрузка не могла перезаписать чужой файл.

-- ---------------------------------------------------------------------------
-- Вложения сообщений
-- ---------------------------------------------------------------------------

CREATE TABLE attachment_model (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    message_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    storage_key VARCHAR(255) NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    size_bytes BIGINT NOT NULL,
    uploaded_by BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT attachment_model_pkey PRIMARY KEY (id),
    CONSTRAINT attachment_model_storage_key_key UNIQUE (storage_key),
    CONSTRAINT attachment_model_size_bytes_check CHECK (size_bytes >= 0)
);

ALTER TABLE attachment_model
    ADD CONSTRAINT fk_attachment_model_message_id FOREIGN KEY (message_id) REFERENCES message_model (id);

ALTER TABLE attachment_model
    ADD CONSTRAINT fk_attachment_model_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES users (id);

-- Лента файлов заявки: выборка по сообщению/заявке, ретро-индекс по дате для отчётов.
CREATE INDEX idx_attachment_model_message_id ON attachment_model (message_id);
CREATE INDEX idx_attachment_model_created_at ON attachment_model (created_at);
