-- Передача владения порталом и история портала.
--
-- Обязательно должен совпадать с entity PortalTransferRequestModel и PortalHistoryModel
-- (src/main/java/com/ukhanov/realhelpdesk/domain/portal/model/):
-- docker-compose держит spring.jpa.hibernate.ddl-auto=validate, и Hibernate валит
-- старт при расхождении таблиц/колонок/типов.
--
-- Каталоги CHECK: по правилам db.changelog-master.xml изменения enum-значений —
-- отдельный changeset с пересозданием ограничения; сюда же добавлены события
-- передачи портала для in-app уведомлений, журнала писем и стоп-листа рассылок.

-- ---------------------------------------------------------------------------
-- Запросы на передачу владения порталом
-- ---------------------------------------------------------------------------

CREATE TABLE portal_transfer_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    portal_id BIGINT NOT NULL,
    initiator_id BIGINT NOT NULL,
    proposed_owner_id BIGINT NOT NULL,
    reason_initiator VARCHAR(2000) NOT NULL,
    reason_proposed VARCHAR(2000),
    keep_old_owner BOOLEAN NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    decided_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT portal_transfer_requests_pkey PRIMARY KEY (id),
    CONSTRAINT portal_transfer_requests_status_check
        CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED', 'EXPIRED'))
);

ALTER TABLE portal_transfer_requests
    ADD CONSTRAINT fk_portal_transfer_requests_portal_id FOREIGN KEY (portal_id) REFERENCES portals (id);

ALTER TABLE portal_transfer_requests
    ADD CONSTRAINT fk_portal_transfer_requests_initiator_id FOREIGN KEY (initiator_id) REFERENCES users (id);

ALTER TABLE portal_transfer_requests
    ADD CONSTRAINT fk_portal_transfer_requests_proposed_owner_id FOREIGN KEY (proposed_owner_id) REFERENCES users (id);

-- Не больше одного активного запроса на портал (истёкшие закрываются лениво при следующем обращении).
CREATE UNIQUE INDEX uq_portal_transfer_requests_pending
    ON portal_transfer_requests (portal_id)
    WHERE status = 'PENDING';

-- Список активных запросов нового владельца (для уведомлений и проверок).
CREATE INDEX idx_portal_transfer_requests_proposed_owner_id
    ON portal_transfer_requests (proposed_owner_id);

-- ---------------------------------------------------------------------------
-- История портала: передачи владения и изменения самого портала
-- ---------------------------------------------------------------------------

CREATE TABLE portal_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    portal_id BIGINT NOT NULL,
    event VARCHAR(40) NOT NULL,
    actor_id BIGINT,
    target_user_id BIGINT,
    reason VARCHAR(2000),
    field_name VARCHAR(40),
    old_value VARCHAR(1000),
    new_value VARCHAR(1000),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT portal_history_pkey PRIMARY KEY (id),
    CONSTRAINT portal_history_event_check
        CHECK (event IN (
            'TRANSFER_REQUESTED', 'TRANSFER_ACCEPTED', 'TRANSFER_REJECTED', 'TRANSFER_CANCELLED', 'TRANSFER_EXPIRED',
            'NAME_CHANGED', 'DESCRIPTION_CHANGED', 'VISIBILITY_CHANGED', 'USERS_CHANGED', 'PORTAL_DELETED'))
);

-- История — аудит: строки не удаляются даже при удалении пользователя, поэтому FK только на портал.
ALTER TABLE portal_history
    ADD CONSTRAINT fk_portal_history_portal_id FOREIGN KEY (portal_id) REFERENCES portals (id);

CREATE INDEX idx_portal_history_portal_id_created ON portal_history (portal_id, created_at);

-- ---------------------------------------------------------------------------
-- Новые события передачи портала в каталогах CHECK
-- ---------------------------------------------------------------------------

ALTER TABLE notifications
    DROP CONSTRAINT notifications_event_check;

ALTER TABLE notifications
    ADD CONSTRAINT notifications_event_check CHECK (event IN ('NEW_TICKET', 'NEW_MESSAGE', 'NEW_SYSTEM_MESSAGE',
        'NEW_TICKET_OR_MESSAGE', 'NEW_PORTAL', 'CHANGE_TICKET', 'RECOVERY_PASSWORD', 'TICKET_DELETED', 'PORTAL_DELETED',
        'PORTAL_TRANSFER_REQUESTED', 'PORTAL_TRANSFER_ACCEPTED', 'PORTAL_TRANSFER_REJECTED', 'PORTAL_TRANSFER_CANCELLED',
        'PORTAL_TRANSFER_EXPIRED', 'NONE'));

ALTER TABLE user_notification_preferences_events
    DROP CONSTRAINT user_notification_preferences_events_event_check;

ALTER TABLE user_notification_preferences_events
    ADD CONSTRAINT user_notification_preferences_events_event_check CHECK (event IN ('NEW_TICKET', 'NEW_MESSAGE',
        'NEW_SYSTEM_MESSAGE', 'NEW_TICKET_OR_MESSAGE', 'NEW_PORTAL', 'CHANGE_TICKET', 'RECOVERY_PASSWORD', 'TICKET_DELETED',
        'PORTAL_DELETED', 'PORTAL_TRANSFER_REQUESTED', 'PORTAL_TRANSFER_ACCEPTED', 'PORTAL_TRANSFER_REJECTED',
        'PORTAL_TRANSFER_CANCELLED', 'PORTAL_TRANSFER_EXPIRED', 'NONE'));

ALTER TABLE email_log
    DROP CONSTRAINT email_log_notification_event_check;

ALTER TABLE email_log
    ADD CONSTRAINT email_log_notification_event_check CHECK (notification_event IN ('NEW_TICKET', 'NEW_MESSAGE',
        'NEW_SYSTEM_MESSAGE', 'NEW_TICKET_OR_MESSAGE', 'NEW_PORTAL', 'CHANGE_TICKET', 'RECOVERY_PASSWORD', 'TICKET_DELETED',
        'PORTAL_DELETED', 'PORTAL_TRANSFER_REQUESTED', 'PORTAL_TRANSFER_ACCEPTED', 'PORTAL_TRANSFER_REJECTED',
        'PORTAL_TRANSFER_CANCELLED', 'PORTAL_TRANSFER_EXPIRED', 'NONE'));

ALTER TABLE unsubscribed_emails
    DROP CONSTRAINT unsubscribed_emails_mute_event_check;

ALTER TABLE unsubscribed_emails
    ADD CONSTRAINT unsubscribed_emails_mute_event_check CHECK (mute_event IN ('NEW_TICKET', 'NEW_MESSAGE', 'NEW_SYSTEM_MESSAGE',
        'NEW_TICKET_OR_MESSAGE', 'NEW_PORTAL', 'CHANGE_TICKET', 'RECOVERY_PASSWORD', 'TICKET_DELETED', 'PORTAL_DELETED',
        'PORTAL_TRANSFER_REQUESTED', 'PORTAL_TRANSFER_ACCEPTED', 'PORTAL_TRANSFER_REJECTED', 'PORTAL_TRANSFER_CANCELLED',
        'PORTAL_TRANSFER_EXPIRED', 'NONE'));
