package com.ukhanov.realhelpdesk.core.mail.model;

public enum NotificationEvent {
    NEW_TICKET, NEW_MESSAGE, NEW_SYSTEM_MESSAGE, NEW_TICKET_OR_MESSAGE, NEW_PORTAL, CHANGE_TICKET, RECOVERY_PASSWORD, TICKET_DELETED,
    PORTAL_DELETED, PORTAL_TRANSFER_REQUESTED, PORTAL_TRANSFER_ACCEPTED, PORTAL_TRANSFER_REJECTED, PORTAL_TRANSFER_CANCELLED,
    PORTAL_TRANSFER_EXPIRED, NONE;
}
